### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by dralley**

### CODE REVIEW

**Comment by smosh** [comment]
Looked pretty good. Thanks.

**Comment by smosh** [comment]
Did pip install pypruss work for you? I didn't know you could do that. I just followed [the author's tutorial on his repo page](https://bitbucket.org/intelligentagent/pypruss)

**Comment by dralley** [comment]
pip just automates running "python setup.py install," so it should work,
but I've never actually verified it on a beaglebone.  It let me run the
pinger without an import error on my own laptop in any case.

You may want to add the ```export LD_LIBRARY_PATH=/usr/local/lib``` step to
the documentation, I guess I forgot about that one

**Comment by dralley** [comment]
Or you can remove it and just recommend the official instructions.  I added it because it's a few less steps and we can also add other required libraries later, but it isn't a big deal and probably isn't necessary atm.

**Comment by smosh** [comment]
Huh, that's strange. I'm kinda surprised that works for you. I try doing that and I get:  
```
root@beaglebone:~/Projects/acoustics# sudo pip install pypruss
Downloading/unpacking pypruss
  Could not find any downloads that satisfy the requirement pypruss
No distributions at all found for pypruss
Storing complete log in /root/.pip/pip.log
```

**Comment by dralley** [comment]
You pypruss isn't on PyPi so that won't work.  But, if you do ```sudo pip install git+git@bitbucket.org:intelligentagent/pypruss.git``` it will clone the project into an anonymous directory and install it

**Comment by smosh** [comment]
Oh, awesome! I didn't know you could do that at all.

**Comment by dralley** [comment]
On second thought though, it may just be better to have people follow his instructions.  I think I'll put it back the way it was before

**Comment by smosh** [comment]
There was about one other dependency mentioned in pinger_finder's README. I was going to copy and paste some of that over eventually. You might just want to let me do that and then we'll go from there.

**Comment by dralley** [comment]
Ok

**Pull request merged**
