### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by dralley**
PENDING TESTING

### CODE REVIEW

**Comment by smosh** [comment]
Why does the highlighted line work? I don't see how "." tells python to go in the bbb directory and look in the __init__.py file.
image

**Comment by smosh** [comment]
`y[chan] *= self.LSB` doesn't work for this code, which is doing element-by-element multiplication. Rather it should be `y[chan] = y[chan]*self.LSB`
image

**Comment by dralley** [comment]
__init__.py is kind of special - it tells python that whatever folder it's in is a package, and when that package is imported the contents of __init__.py are the very first code that is run.  Everything defined inside that file is given global package-level scope.

So defining BIN_DIR in __init__.py will make it a variable of the package itself rather than any module in the package (like if you put it in an init.py file) and ```from . import BIN_DIR``` works fine.

-----------------------------------

I'm not sure whether or not numpy overloads the *= operator, so I'll put it back the way it was.  You might be right there.

**Comment by dralley** [comment]
Testing worked then?

**Comment by smosh** [comment]
Yup. Thanks! Had to change a couple things, but Everything still works and looks good.

**Pull request merged**
